{{- if and (.Capabilities.APIVersions.Has "jenkins.io/v1/Release") (hasKey .Values.jx "releaseCRD") (.Values.jx.releaseCRD)}}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-03-29T12:56:55Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: v.behar@free.fr
      name: Vincent Behar
    branch: master
    committer:
      email: v.behar@free.fr
      name: Vincent Behar
    message: |
      chore: add a first (home) dashboard
    sha: 87cb25f2d787b5789e8174ac8d3e0ab087139fac
  - author:
      email: v.behar@free.fr
      name: Vincent Behar
    branch: master
    committer:
      email: v.behar@free.fr
      name: Vincent Behar
    message: |
      fix: chart
    sha: 820366cd3778d97d84f7ae2dcd0fac11c3bad424
  gitHttpUrl: https://github.com/jenkins-x/cd-indicators
  gitOwner: jenkins-x
  gitRepository: cd-indicators
  name: '{{ .Chart.Name }}'
  version: 0.0.8
status: {}
 
{{- end }}
